### ISSUE TITLE
Misspelling a chart name has confusing behaviour

### ISSUE THREAD

**Issue by jaxxstorm** [bitnami-labs/helm-crd#26]
I created a helmrelease but misspelled the chart name:

```
apiVersion: helm.bitnami.com/v1
kind: HelmRelease
metadata:
  name: helm-redis
spec:
  # 'stable' repo
  repoUrl: https://kubernetes-charts.storage.googleapis.com
  chartName: reds
  version: 3.2.1
  values: |
    usePassword: true
```

It created the redis deployment and the HelmRelease object:

```
NAME         AGE
helm-redis   40s
```

But no deployment or pod was ever created
